# Generated by Django 2.2.9 on 2020-09-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voluntarios',
            new_name='Voluntario',
        ),
    ]
