# Generated by Django 2.2.9 on 2020-09-21 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
        ('voluntarios', '0002_auto_20200921_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicoes.Instituicao'),
        ),
    ]
