# Generated by Django 2.2.9 on 2020-09-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='despesas',
            field=models.ManyToManyField(to='despesas.Despesa'),
        ),
    ]
